### ISSUE TITLE
【bug】Base Set and tp Report errors

### ISSUE THREAD

**Issue by dark7666** [TSEcho/PokeTeams#12]
[02:41:54] [Server thread/INFO] [nucleus]: dark7 执行指令: /team base
[02:41:54] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'team base' for source EntityPlayerMP['dark7'/143, l='world', x=-47.42, y=72.00, z=329.47]: null
java.lang.NullPointerException: null
	at java.util.UUID.fromString(Unknown Source) ~[?:1.8.0_201]
	at io.github.TSEcho.PokeTeams.Commands.Bases.BasesBase.execute(BasesBase.java:40) ~[BasesBase.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:250) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.5]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.5]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.5]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.5]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.5]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.5]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[02:42:21] [Server thread/INFO] [nucleus]: dark7 执行指令: /team base
[02:42:21] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'team base' for source EntityPlayerMP['dark7'/143, l='world', x=-51.68, y=72.00, z=335.88]: null
java.lang.NullPointerException: null
	at java.util.UUID.fromString(Unknown Source) ~[?:1.8.0_201]
	at io.github.TSEcho.PokeTeams.Commands.Bases.BasesBase.execute(BasesBase.java:40) ~[BasesBase.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:250) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.5]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.5]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.5]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.5]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.5]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.5]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]

[02:40:00] [Server thread/INFO] [nucleus]: dark7 执行指令: /team base set
[02:40:00] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'team base set' for source EntityPlayerMP['dark7'/43, l='world', x=-46.99, y=72.00, z=329.40]: Configuration does not accept objects of type class java.util.UUID
java.lang.IllegalArgumentException: Configuration does not accept objects of type class java.util.UUID
	at ninja.leaping.configurate.ScalarConfigValue.setValue(ScalarConfigValue.java:51) ~[spongeforge-1.12.2-2768-7.1.5.jar:1.12.2-2768-7.1.5]
	at ninja.leaping.configurate.SimpleConfigurationNode.insertNewValue(SimpleConfigurationNode.java:318) ~[spongeforge-1.12.2-2768-7.1.5.jar:1.12.2-2768-7.1.5]
	at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:283) ~[spongeforge-1.12.2-2768-7.1.5.jar:1.12.2-2768-7.1.5]
	at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:87) ~[spongeforge-1.12.2-2768-7.1.5.jar:1.12.2-2768-7.1.5]
	at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:33) ~[spongeforge-1.12.2-2768-7.1.5.jar:1.12.2-2768-7.1.5]
	at io.github.TSEcho.PokeTeams.APIs.PokeTeamsAPI.setBase(PokeTeamsAPI.java:253) ~[PokeTeamsAPI.class:?]
	at io.github.TSEcho.PokeTeams.Commands.Bases.Set.execute(Set.java:39) ~[Set.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.5]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.5]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.5]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.5]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.5]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.5]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by dark7666** [comment]
And the list cannot be displayed in matching battles

**Comment by dark7666** [comment]
The number of Poke defeated is not shown correctly

**Comment by dark7666** [comment]
Some instructions correspond to incorrect information

**Comment by TSEcho** [comment]
Please follow the guide for submitting bugs. I’m not sure what you mean by most of these because of lack of information.

For the first one, try to get the player to set their base again. If I remember correctly worlds are factored in again so if you changed the world names at all it’d create problems. Also if they created a base long ago it’d create problems.

The other ones you submitted I do not understand.
