### ISSUE TITLE
[bug]The latest version will report errors

### ISSUE THREAD

**Issue by dark7666** [TSEcho/PokeTeams#9]
[05:28:29] [Server thread/ERROR] [FML]: Exception caught during firing event com.pixelmonmod.pixelmon.api.events.battles.BattleEndEvent@58cdffe6:
java.lang.NullPointerException: null
	at io.github.TSEcho.PokeTeams.APIs.PokeTeamsAPI.<init>(PokeTeamsAPI.java:24) ~[PokeTeamsAPI.class:?]
	at io.github.TSEcho.PokeTeams.Pixelmon.BattleManager.onEndBattle(BattleManager.java:45) ~[BattleManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_219_BattleManager_onEndBattle_BattleEndEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:747) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:697) [EventBus.class:?]
	at com.pixelmonmod.pixelmon.battles.controller.BattleControllerBase.endBattle(BattleControllerBase.java:752) [BattleControllerBase.class:?]
	at com.pixelmonmod.pixelmon.battles.controller.BattleControllerBase.endBattle(BattleControllerBase.java:631) [BattleControllerBase.class:?]
	at com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.storeCapture(EntityEmptyPokeball.java:337) [EntityEmptyPokeball.class:?]
	at com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.func_70071_h_(EntityEmptyPokeball.java:304) [EntityEmptyPokeball.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:157) [TrackingUtil.class:1.12.2-2768-7.1.5]
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zmc000(WorldServer.java:2978) [oo.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:4157) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1955) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6599) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2290) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[05:28:29] [Server thread/ERROR] [FML]: Index: 4 Listeners:
[05:28:29] [Server thread/ERROR] [FML]: 0: NORMAL
[05:28:29] [Server thread/ERROR] [FML]: 1: ASM: rs.expand.pixelmonbroadcasts.listeners.BattleEndListener@5cea8edb onBattleEndEvent(Lcom/pixelmonmod/pixelmon/api/events/battles/BattleEndEvent;)V
[05:28:29] [Server thread/ERROR] [FML]: 2: ASM: com.pixelmonmod.pixelmon.PixelmonEventHandler@46eb5df6 onBattleEnd(Lcom/pixelmonmod/pixelmon/api/events/battles/BattleEndEvent;)V
[05:28:29] [Server thread/ERROR] [FML]: 3: ASM: com.hiroku.tournaments.listeners.BattleListener@643e9d67 onBattleEnd(Lcom/pixelmonmod/pixelmon/api/events/battles/BattleEndEvent;)V
[05:28:29] [Server thread/ERROR] [FML]: 4: ASM: io.github.TSEcho.PokeTeams.Pixelmon.BattleManager@6fb80123 onEndBattle(Lcom/pixelmonmod/pixelmon/api/events/battles/BattleEndEvent;)V
[05:28:29] [Server thread/ERROR] [FML]: 5: ASM: com.pixelmonmod.pixelmon.listener.PokerusSpreader@7e367270 onBattleEnd(Lcom/pixelmonmod/pixelmon/api/events/battles/BattleEndEvent;)V
[05:28:29] [Server thread/ERROR] [Sponge]: /********************************************************************************************************************************/
[05:28:29] [Server thread/ERROR] [Sponge]: /*                                            Exception occurred during a PhaseState                                            */
[05:28:29] [Server thread/ERROR] [Sponge]: /********************************************************************************************************************************/
[05:28:29] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system makes a best effort to not throw exceptions randomly                                                */
[05:28:29] [Server thread/ERROR] [Sponge]: /* but sometimes it is inevitable. In most cases, something else triggered this                                                 */
[05:28:29] [Server thread/ERROR] [Sponge]: /* exception and Sponge prevented a crash by catching it. The following stacktrace                                              */
[05:28:29] [Server thread/ERROR] [Sponge]: /* can be used to help pinpoint the cause.                                                                                      */
[05:28:29] [Server thread/ERROR] [Sponge]: /********************************************************************************************************************************/
[05:28:29] [Server thread/ERROR] [Sponge]: /* The PhaseState having an exception: EntityTickPhase                                                                          */
[05:28:29] [Server thread/ERROR] [Sponge]: /* The PhaseContext:                                                                                                            */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     - Owner: EntityPlayerMP['Mr_Rabbit'/104, l='world', x=-3599.84, y=72.00, z=2805.97]                                      */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     - Source: EntityEmptyPokeball['超级球'/601, l='world', x=-3602.00, y=72.05, z=2807.00]                                      */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     - CapturedBlockPosition: CaptureBlockPos{pos=null, world=Optional.empty}                                                 */
[05:28:29] [Server thread/ERROR] [Sponge]: /* org.spongepowered.asm.util.PrettyPrinter@59b37def                                                                            */
[05:28:29] [Server thread/ERROR] [Sponge]: /********************************************************************************************************************************/
[05:28:29] [Server thread/ERROR] [Sponge]: /* StackTrace:                                                                                                                  */
[05:28:29] [Server thread/ERROR] [Sponge]: /* java.lang.NullPointerException: null                                                                                         */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     io.github.TSEcho.PokeTeams.APIs.PokeTeamsAPI.<init>(PokeTeamsAPI.java:24)                                                */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     io.github.TSEcho.PokeTeams.Pixelmon.BattleManager.onEndBattle(BattleManager.java:45)                                     */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.ASMEventHandler_219_BattleManager_onEndBattle_BattleEndEvent.invoke(.dynamic) */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)                               */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:747)                                              */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:697)                                              */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.battles.controller.BattleControllerBase.endBattle(BattleControllerBase.java:752)                */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.battles.controller.BattleControllerBase.endBattle(BattleControllerBase.java:631)                */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.storeCapture(EntityEmptyPokeball.java:337)               */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     com.pixelmonmod.pixelmon.entities.pokeballs.EntityEmptyPokeball.func_70071_h_(EntityEmptyPokeball.java:304)              */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:157)                                   */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zmc000(WorldServer.java:2978)                                */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72866_a(World.java:4157)                                                                  */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)                                                       */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72870_g(World.java:1955)                                                                  */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.World.func_72939_s(World.java:6599)                                                                  */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2290)                                                      */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)                                              */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)                                    */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)                                              */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)                                                       */
[05:28:29] [Server thread/ERROR] [Sponge]: /*     java.lang.Thread.run(Unknown Source)                                                                                     */
[05:28:29] [Server thread/ERROR] [Sponge]: /*  Phases Remaining:                                                                                                           */
[05:28:29] [Server thread/ERROR] [Sponge]: /*                                                                                                                              */
[05:28:29] [Server thread/ERROR] [Sponge]: /* Minecraft : 1.12.2                                                                                                           */
[05:28:29] [Server thread/ERROR] [Sponge]: /* SpongeAPI : 7.1.0-366290f8                                                                                                   */
[05:28:29] [Server thread/ERROR] [Sponge]: /* Sponge : 1.12.2-7.1.5                                                                                                        */
[05:28:29] [Server thread/ERROR] [Sponge]: /* SpongeForge : 1.12.2-2768-7.1.5                                                                                              */
[05:28:29] [Server thread/ERROR] [Sponge]: /* Minecraft Forge : 14.23.5.2768                                                                                               */
[05:28:29] [Server thread/ERROR] [Sponge]: /********************************************************************************************************************************/

**Comment by TSEcho** [comment]
Yup in progress of fixing and will be good next update
